exclude: [
    LICENSE,
    Resources,
    Gemfile,
    Gemfile.lock,
    calendar.html,
    clock.html,
    container.html]
baseurl: /ChaosClock
sass:

    # loading path from site root (defaults to _sass)
    sass_dir: _includes/css

    # style: :nested (default), :compact, :compressed, :expanded
    style: :compressed
